#!/usr/bin/env bash
set -euf -o pipefail

cp index.js index.js.orig
trap 'mv index.js.orig index.js' EXIT

gawk '
  {
    if ($0 == "//. <pre>") {
      pre = 1 ; print
    } else if ($0 == "//. </pre>") {
      pre = 0 ; print
    } else if (pre) {
      print gensub(/[[:alnum:]]+/, "<a href=\"#&\">&</a>", "g")
    } else {
      print
    }
  }
' index.js.orig >index.js

node_modules/.bin/sanctuary-generate-readme
