#!/usr/bin/env node

'use strict';

var fs = require('fs');


//  definitions :: Array String
var definitions = [
  "global.Identity = require('./test/Identity')",
  "global.List = require('./test/List')",
  'global.Nil = List.Nil',
  'global.Cons = List.Cons',
  "global.Maybe = require('./test/Maybe')",
  'global.Nothing = Maybe.Nothing',
  'global.Just = Maybe.Just',
  "global.Tuple = require('./test/Tuple')"
];

process.stdout.write(
  fs.readFileSync('index.js', {encoding: 'utf8'})
  .replace(/^(.*)( ```javascript\n)\1 > (.*)/m,
           '$1$2$1 > ' + definitions.join(', ') + ', $3')
  .split(/(```javascript[\s\S]*?```)/g)
  .map(function(s, idx) {
    return idx % 2 === 1 ? s : s.replace(/^([ ]*[/][/][.]) >/gm, '$1');
  })
  .join('')
);
