#!/usr/bin/env bash
set -euf -o pipefail

trap 'rm node_modules/fantasy-laws/node_modules/sanctuary-type-classes' EXIT

# Force fantasy-laws to use the current version of sanctuary-type-classes.
# <https://github.com/sanctuary-js/sanctuary-type-classes/pull/89#discussion_r171182845>
mkdir -p node_modules/fantasy-laws/node_modules
ln -s ../../.. node_modules/fantasy-laws/node_modules/sanctuary-type-classes

# Patch fantasy-laws import declarations for compatibility with this version
# of sanctuary-type-classes. Patching will not be necessary once fantasy-laws
# depends on a version of sanctuary-type-classes that uses ESM.
prog=$'$0 == "import Z from \'sanctuary-type-classes\';" { $2 = "* as Z" } { print }'
find node_modules/fantasy-laws/src -name '*.js' -print0 | xargs -0 -n 1 sh -c 'awk "$0" "$1" >"$1.tmp" && mv "$1.tmp" "$1"' "$prog"

node_modules/.bin/sanctuary-test "$@"
